# version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nxagent-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - RUN_MIGRATIONS=true
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: ["./start.sh"]

volumes:
  postgres-data:
