# version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hct-knowup-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - RUN_MIGRATIONS=true
